//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PotionBook.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class IngredientOne
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IngredientOne()
        {
            this.Potions = new HashSet<Potion>();
        }
    
        public int idOne { get; set; }
        public string NameOne { get; set; }
        public string ImageOne { get; set; }

        public string CorrectPhoto
        {
            get
            {
                if (String.IsNullOrEmpty(ImageOne) || String.IsNullOrWhiteSpace(ImageOne))
                {
                    return "/Resources/icon.png";
                }
                else
                {
                    return "/Resources/" + ImageOne;
                }
            }
        }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Potion> Potions { get; set; }
    }
}
