//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PotionBook.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Potion
    {
        public int id { get; set; }
        public string Name { get; set; }
        public int IngredientOne { get; set; }
        public string NameIngredientOne
        {
            get
            {
                return IngredientOne1.NameOne.ToString();
            }
        }
        public int IngredientTwo { get; set; }
        public string NameIngredientTwo
        {
            get
            {
                if (String.IsNullOrEmpty(IngredientTwo.ToString()) || String.IsNullOrWhiteSpace(IngredientTwo.ToString()))
                {
                    return "";
                }
                else
                {
                    return IngredientTwo1.NameTwo.ToString();
                }
            }
        }
        public int IngredientThr { get; set; }
        public string NameIngredientThr
        {
            get
            {
                if (String.IsNullOrEmpty(IngredientThr.ToString()) || String.IsNullOrWhiteSpace(IngredientThr.ToString()))
                {
                    return "";
                }
                else
                {
                    return IngredientThr1.NameThr.ToString();
                }
            }
        }
        public int IngredientFour { get; set; }
        public string NameIngredientFour
        {
            get
            {
                if (IngredientFour.ToString() == null || String.IsNullOrEmpty(IngredientFour.ToString()) || String.IsNullOrWhiteSpace(IngredientFour.ToString()))
                {
                    return "";
                }
                else
                {
                    return IngredientFour1.NameFour.ToString();
                }
            }
        }
        public string Image { get; set; }
        public string CorrectImage
        {
            get
            {
                if (String.IsNullOrEmpty(Image) || String.IsNullOrWhiteSpace(Image))
                {
                    return "Properties/Resources/icon";
                }
                else
                {
                    return "Propetries/Resources/" + Image;
                }
            }
        }

        public virtual IngredientFour IngredientFour1 { get; set; }
        public virtual IngredientOne IngredientOne1 { get; set; }
        public virtual IngredientThr IngredientThr1 { get; set; }
        public virtual IngredientTwo IngredientTwo1 { get; set; }
    }
}
