//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PotionBook.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Potion
    {
        public int id { get; set; }
        public string Name { get; set; }
        public int IngredientOne { get; set; }
        public Nullable<int> IngredientTwo { get; set; }
        public Nullable<int> IngredientThr { get; set; }
        public Nullable<int> IngredientFour { get; set; }
    
        public virtual Ingredient Ingredient { get; set; }
        public virtual Ingredient Ingredient1 { get; set; }
        public virtual Ingredient Ingredient2 { get; set; }
        public virtual Ingredient Ingredient3 { get; set; }
    }
}
